### ISSUE TITLE
how to use FollowIR-7B to calculate nDCG

### ISSUE THREAD

**Issue by SighingSnow** [orionw/FollowIR#6]
Hey, I have read example the https://huggingface.co/jhu-clsp/FollowIR-7B and know how to compute similarity scores using FollowIR-7B. 
And I have also checked https://github.com/orionw/promptriever/blob/cde6c3a18ae94389e421c8171cc884f7946ed326/scripts/filtering/filter_query_doc_pairs_from_batch_gpt.py on how to use FollowIR-7B with BEIR. But I am wondering how to calculate nDCG and other metrics in both two papers.

**Comment by orionw** [comment]
Hi @SighingSnow and thanks for the interest!

The easiest way to use it with MTEB datasets is to run it with MTEB. If you want to evaluate a custom dataset, you can either add that dataset to MTEB or take the evaluation from it (it uses pytrec_eval). 

For an example of running with a MTEB dataset, see [this line about the command](https://github.com/orionw/FollowIR/blob/master/evaluate_any.py#L52) and [you can change the dataset called in this line](https://github.com/orionw/FollowIR/blob/master/models/rerankers/evaluate_reranker.py#L35).

Let me know if you have any other questions!

**Comment by SighingSnow** [comment]
Thanks for your timely reply. 

> you can either add that dataset to MTEB or take the evaluation from it (it uses pytrec_eval).

Does this mean I should check how pytrec_eval calls FollowIR-7B, and then customize it to meet my needs, right?

**Comment by orionw** [comment]
> Does this mean I should check how pytrec_eval calls FollowIR-7B, and then customize it to meet my needs, right?

Do you have a new custom dataset not in MTEB? Then yes, you can either add that dataset to MTEB (we always welcome new dataset contributions) or perform a similar eval.  

If you don't need p-MRR then you can easily calculate standard metrics like nDCG with pytrec_eval, see the examples here: https://github.com/cvangysel/pytrec_eval. I have also heard good things about [ranx](https://amenra.github.io/ranx/) but haven't used it. For both, you need to ranked list and the qrels and it will calculate all the metrics you need.

If you need p-MRR you can copy/modify the eval code from [MTEB here](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/evaluators/utils.py#L236).

**Comment by SighingSnow** [comment]
> Do you have a new custom dataset not in MTEB? Then yes, you can either add that dataset to MTEB (we always welcome new dataset contributions) or perform a similar eval.

Yes,  we are considering adding this dataset to mteb. But our previous pipeline is different from MTEB.  We want to check the FollowIR-7B performance using our own pipeline.

> If you don't need p-MRR then you can easily calculate standard metrics like nDCG with pytrec_eval, see the examples here: https://github.com/cvangysel/pytrec_eval.

What confuses me is that it seems that **we cannot use FollowIR-7B to generate embeddings directly**, I mainly ref this page https://huggingface.co/jhu-clsp/FollowIR-7B. It seem not friendly when there are large amount of passages.

**Comment by orionw** [comment]
> What confuses me is that it seems that we cannot use FollowIR-7B to generate embeddings directly, I mainly ref this page https://huggingface.co/jhu-clsp/FollowIR-7B. It seem not friendly when there are large amount of passages.

Ah, thanks for the clarification! Yes, FollowIR-7B is a cross-encoder model (similar to MonoT5, etc.) that should be used for reranking - it does not produce embeddings. Rerankers aren't generally used for more than 1k passages because they are very expensive to run, as you mention. If you want to evaluate FollowIR-7B from a new collection, you'll need to get the first stage results (e.g. run some other embedding/bm25 model first) and then rerank the top 1000 or so from that.  

If you're looking for an embedding model like FollowIR-7B, that would be our [Promptriever model](https://huggingface.co/samaya-ai/promptriever-llama2-7b-v1).  You can use this model for embeddings similar to RepLLaMA, E5, etc.

**Comment by SighingSnow** [comment]
> If you want to evaluate FollowIR-7B from a new collection, you'll need to get the first stage results (e.g. run some other embedding/bm25 model first) and then rerank the top 1000 or so from that.

This completely solves my problem. Thank you for your patient answers. I will go ahead and close this issue.

>  If you're looking for an embedding model like FollowIR-7B, that would be our [Promptriever model](https://huggingface.co/samaya-ai/promptriever-llama2-7b-v1).

Yes, that's an excellent work! We are very interested in it.
